query getPost($id: Int!) {
  post(where: { id: $id }) {
    id
    title
    content
  }
}

query getPosts {
  posts {
    id
    title
  }
}

mutation createPost($email: String!, $title: String!) {
  createPost(
    data: {
      title: $title
      content: "Woooooow"
      author: {
        connectOrCreate: { create: { email: $email }, where: { email: $email } }
      }
    }
  ) {
    id
  }
}

mutation createUser($email: String!) {
  createUser(data: { email: $email }) {
    id
  }
}
