query getPost($id: Int!) {
  post(where: { id: $id }) {
    id
    title
    content
    author {
      name
    }
  }
}

query getPosts {
  posts {
    id
    title
  }
}

mutation createPost($email: String!, $title: String!) {
  createPost(
    data: {
      title: $title
      content: "Woooooow"
      author: {
        connectOrCreate: {
          create: { name: "Andrius", email: $email }
          where: { email: $email }
        }
      }
    }
  ) {
    id
  }
}
